# Generated by Django 4.2.5 on 2023-10-05 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitclone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=300)),
                ('post_time', models.DateField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='twitclone.profile')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitclone.profile')),
            ],
        ),
    ]
